# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'afNetWorkingEx' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'


pod 'AFNetworking', '~> 3.0'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for afNetWorkingEx

  target 'afNetWorkingExTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'afNetWorkingExUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
