# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AllMyPasswords' do
pod 'ObjectiveDropboxOfficial'
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AllMyPasswords

  target 'AllMyPasswordsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AllMyPasswordsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
