# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AFNetworkingExample' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AFNetworkingExample

  target 'AFNetworkingExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AFNetworkingExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
