# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AfNetWithDelegate' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking', '~> 3.0'

  # Pods for AfNetWithDelegate

  target 'AfNetWithDelegateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AfNetWithDelegateUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
