# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AEExchange' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AEExchange
pod 'AFNetworking', '~> 3.0'
  target 'AEExchangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AEExchangeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
