# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GooglntegrationDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'Google/SignIn'
  # Pods for GooglntegrationDemo

  target 'GooglntegrationDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GooglntegrationDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
